/******************************************************************************************
  Filename    : aiao.h

  Core        : T-Head XuanTie C906 (RV64)
  
  SoC         : CVITEK CV1800B (Milk-V Duo)
    
  Author      : emeb
 
  Owner       : emeb
  
  Date        : 04.18.2026
  
  Description : AIAO peripheral header file
  
******************************************************************************************/

#ifndef AIAO_H
#define AIAO_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @struct  AIAO_TypeDef
 * @brief   AIAO Register Layout
 */
typedef struct {
    volatile uint32_t i2s_tdm_sclk_in_sel;	/* 0x000: Select the source of TX/RX module’ SCLK in slave mode. */
	volatile uint32_t i2s_tdm_fs_in_sel;	/* 0x004: Select the source of TX/RX module’s frame synchronizing signal in slave mode.*/
	volatile uint32_t i2s_tdm_sdi_in_sel;	/* 0x008: Select the source of RX module’s SDI signal. */
	volatile uint32_t i2s_tdm_sdo_out_sel;	/* 0x00c: Select the source of subsystem’s SDO output. */
	uint32_t RESERVED_0[8];					/* 0x010 - 0x02c */
	volatile uint32_t i2s_bclk_oen_sel;		/* 0x030: The output control of BCLK IO. */
	uint32_t RESERVED_1[3];					/* 0x034 - 0x03c */
	volatile uint32_t audio_pdm_ctrl;		/* 0x040: Enable PDM mode. */
	uint32_t RESERVED_2[7];					/* 0x044 - 0x05c */
	volatile uint32_t i2s_sys_int_en;		/* 0x060: */
	volatile uint32_t i2s_sys_ints;			/* 0x064: */
} AIAO_TypeDef;

/* Peripheral Base Definitions */
#define AIAO_BASE    (0x04108000ull)

/* Instance Pointers */
#define AIAO    ((AIAO_TypeDef *)AIAO_BASE)

/* Register fields */
#define AIAO_I2S_TDM_0_SCLK_IN_SEL_POS (0)
#define AIAO_I2S_TDM_0_SCLK_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_0_SCLK_IN_SEL_POS)
#define AIAO_I2S_TDM_0_SCLK_IN_SEL_I2S_TDM_1_BCLK_OUT (1)
#define AIAO_I2S_TDM_0_SCLK_IN_SEL_I2S_TDM_2_BCLK_OUT (2)
#define AIAO_I2S_TDM_0_SCLK_IN_SEL_I2S_TDM_3_BCLK_OUT (3)
#define AIAO_I2S_TDM_0_SCLK_IN_SEL_BCLK_IN_I2S0 (4)
#define AIAO_I2S_TDM_0_SCLK_IN_SEL_BCLK_IN_I2S1 (5)
#define AIAO_I2S_TDM_0_SCLK_IN_SEL_BCLK_IN_I2S2 (6)
#define AIAO_I2S_TDM_0_SCLK_IN_SEL_BCLK_IN_I2S3 (7)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_POS (4)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_1_SCLK_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_I2S_TDM_0_BCLK_OUT (0<<4)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_INTERNAL_AUDIO_PDM_I2S_SCK (1<<4)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_I2S_TDM_2_BCLK_OUT (2<<4)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_I2S_TDM_3_BCLK_OUT (3<<4)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_BCLK_IN_I2S0 (4<<4)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_BCLK_IN_I2S1 (5<<4)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_BCLK_IN_I2S2 (6<<4)
#define AIAO_I2S_TDM_1_SCLK_IN_SEL_BCLK_IN_I2S3 (7<<4)
#define AIAO_I2S_TDM_2_SCLK_IN_SEL_POS (8)
#define AIAO_I2S_TDM_2_SCLK_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_2_SCLK_IN_SEL_POS)
#define AIAO_I2S_TDM_2_SCLK_IN_SEL_I2S_TDM_0_BCLK_OUT (0<<8)
#define AIAO_I2S_TDM_2_SCLK_IN_SEL_I2S_TDM_1_BCLK_OUT (1<<8)
#define AIAO_I2S_TDM_2_SCLK_IN_SEL_I2S_TDM_3_BCLK_OUT (3<<8)
#define AIAO_I2S_TDM_2_SCLK_IN_SEL_BCLK_IN_I2S0 (4<<8)
#define AIAO_I2S_TDM_2_SCLK_IN_SEL_BCLK_IN_I2S1 (5<<8)
#define AIAO_I2S_TDM_2_SCLK_IN_SEL_BCLK_IN_I2S2 (6<<8)
#define AIAO_I2S_TDM_2_SCLK_IN_SEL_BCLK_IN_I2S3 (7<<8)
#define AIAO_I2S_TDM_3_SCLK_IN_SEL_POS (12)
#define AIAO_I2S_TDM_3_SCLK_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_3_SCLK_IN_SEL_POS)
#define AIAO_I2S_TDM_3_SCLK_IN_SEL_I2S_TDM_0_BCLK_OUT (0<<12)
#define AIAO_I2S_TDM_3_SCLK_IN_SEL_I2S_TDM_1_BCLK_OUT (1<<12)
#define AIAO_I2S_TDM_3_SCLK_IN_SEL_I2S_TDM_2_BCLK_OUT (2<<12)
#define AIAO_I2S_TDM_3_SCLK_IN_SEL_BCLK_IN_I2S0 (4<<12)
#define AIAO_I2S_TDM_3_SCLK_IN_SEL_BCLK_IN_I2S1 (5<<12)
#define AIAO_I2S_TDM_3_SCLK_IN_SEL_BCLK_IN_I2S2 (6<<12)
#define AIAO_I2S_TDM_3_SCLK_IN_SEL_BCLK_IN_I2S3 (7<<12)

#define AIAO_I2S_TDM_0_FS_IN_SEL_POS (0)
#define AIAO_I2S_TDM_0_FS_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_0_FS_IN_SEL_POS)
#define AIAO_I2S_TDM_0_FS_IN_SEL_I2S_TDM_1_FS_OUT (1)
#define AIAO_I2S_TDM_0_FS_IN_SEL_I2S_TDM_2_FS_OUT (2)
#define AIAO_I2S_TDM_0_FS_IN_SEL_I2S_TDM_3_FS_OUT (3)
#define AIAO_I2S_TDM_0_FS_IN_SEL_FS_IN_I2S0 (4)
#define AIAO_I2S_TDM_0_FS_IN_SEL_FS_IN_I2S1 (5)
#define AIAO_I2S_TDM_0_FS_IN_SEL_FS_IN_I2S2 (6)
#define AIAO_I2S_TDM_0_FS_IN_SEL_FS_IN_I2S3 (7)
#define AIAO_I2S_TDM_1_FS_IN_SEL_POS (4)
#define AIAO_I2S_TDM_1_FS_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_1_FS_IN_SEL_POS)
#define AIAO_I2S_TDM_1_FS_IN_SEL_I2S_TDM_0_FS_OUT (0<<4)
#define AIAO_I2S_TDM_1_FS_IN_SEL_INTERNAL_AUDIO_PDM_I2S_FS (1<<4)
#define AIAO_I2S_TDM_1_FS_IN_SEL_I2S_TDM_2_FS_OUT (2<<4)
#define AIAO_I2S_TDM_1_FS_IN_SEL_I2S_TDM_3_FS_OUT (3<<4)
#define AIAO_I2S_TDM_1_FS_IN_SEL_FS_IN_I2S0 (4<<4)
#define AIAO_I2S_TDM_1_FS_IN_SEL_FS_IN_I2S1 (5<<4)
#define AIAO_I2S_TDM_1_FS_IN_SEL_FS_IN_I2S2 (6<<4)
#define AIAO_I2S_TDM_1_FS_IN_SEL_FS_IN_I2S3 (7<<4)
#define AIAO_I2S_TDM_2_FS_IN_SEL_POS (8)
#define AIAO_I2S_TDM_2_FS_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_2_FS_IN_SEL_POS)
#define AIAO_I2S_TDM_2_FS_IN_SEL_I2S_TDM_0_FS_OUT (0<<8)
#define AIAO_I2S_TDM_2_FS_IN_SEL_I2S_TDM_1_FS_OUT (1<<8)
#define AIAO_I2S_TDM_2_FS_IN_SEL_I2S_TDM_3_FS_OUT (3<<8)
#define AIAO_I2S_TDM_2_FS_IN_SEL_FS_IN_I2S0 (4<<8)
#define AIAO_I2S_TDM_2_FS_IN_SEL_FS_IN_I2S1 (5<<8)
#define AIAO_I2S_TDM_2_FS_IN_SEL_FS_IN_I2S2 (6<<8)
#define AIAO_I2S_TDM_2_FS_IN_SEL_FS_IN_I2S3 (7<<8)
#define AIAO_I2S_TDM_3_FS_IN_SEL_POS (12)
#define AIAO_I2S_TDM_3_FS_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_3_FS_IN_SEL_POS)
#define AIAO_I2S_TDM_3_FS_IN_SEL_I2S_TDM_0_FS_OUT (0<<12)
#define AIAO_I2S_TDM_3_FS_IN_SEL_I2S_TDM_1_FS_OUT (1<<12)
#define AIAO_I2S_TDM_3_FS_IN_SEL_I2S_TDM_2_FS_OUT (2<<12)
#define AIAO_I2S_TDM_3_FS_IN_SEL_FS_IN_I2S0 (4<<12)
#define AIAO_I2S_TDM_3_FS_IN_SEL_FS_IN_I2S1 (5<<12)
#define AIAO_I2S_TDM_3_FS_IN_SEL_FS_IN_I2S2 (6<<12)
#define AIAO_I2S_TDM_3_FS_IN_SEL_FS_IN_I2S3 (7<<12)

#define AIAO_I2S_TDM_0_SDI_IN_SEL_POS (0)
#define AIAO_I2S_TDM_0_SDI_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_0_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_0_SDI_IN_SEL_I2S_TDM_1_SDO_OUT (0x1<<AIAO_I2S_TDM_0_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_0_SDI_IN_SEL_I2S_TDM_2_SDO_OUT (0x2<<AIAO_I2S_TDM_0_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_0_SDI_IN_SEL_I2S_TDM_3_SDO_OUT (0x3<<AIAO_I2S_TDM_0_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_0_SDI_IN_SEL_SDI_IN_I2S0 (0x4<<AIAO_I2S_TDM_0_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_0_SDI_IN_SEL_SDI_IN_I2S1 (0x5<<AIAO_I2S_TDM_0_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_0_SDI_IN_SEL_SDI_IN_I2S2 (0x6<<AIAO_I2S_TDM_0_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_0_SDI_IN_SEL_SDI_IN_I2S3 (0x7<<AIAO_I2S_TDM_0_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_POS (4)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_1_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_I2S_TDM_0_SDO_OUT (0x0<<AIAO_I2S_TDM_1_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_INTERNAL_AUDIO_PDM_I2S_SDATA (0x1<<AIAO_I2S_TDM_1_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_I2S_TDM_2_SDO_OUT (0x2<<AIAO_I2S_TDM_1_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_I2S_TDM_3_SDO_OUT (0x3<<AIAO_I2S_TDM_1_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_SDI_IN_I2S0 (0x4<<AIAO_I2S_TDM_1_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_SDI_IN_I2S1 (0x5<<AIAO_I2S_TDM_1_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_SDI_IN_I2S2 (0x6<<AIAO_I2S_TDM_1_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_1_SDI_IN_SEL_SDI_IN_I2S3 (0x7<<AIAO_I2S_TDM_2_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_2_SDI_IN_SEL_POS (8)
#define AIAO_I2S_TDM_2_SDI_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_2_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_2_SDI_IN_SEL_I2S_TDM_0_SDO_OUT (0x0<<AIAO_I2S_TDM_2_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_2_SDI_IN_SEL_I2S_TDM_1_SDO_OUT (0x1<<AIAO_I2S_TDM_2_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_2_SDI_IN_SEL_I2S_TDM_3_SDO_OUT (0x3<<AIAO_I2S_TDM_2_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_2_SDI_IN_SEL_SDI_IN_I2S0 (0x4<<AIAO_I2S_TDM_2_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_2_SDI_IN_SEL_SDI_IN_I2S1 (0x5<<AIAO_I2S_TDM_2_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_2_SDI_IN_SEL_SDI_IN_I2S2 (0x6<<AIAO_I2S_TDM_2_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_2_SDI_IN_SEL_SDI_IN_I2S3 (0x7<<AIAO_I2S_TDM_2_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_3_SDI_IN_SEL_POS (12)
#define AIAO_I2S_TDM_3_SDI_IN_SEL_MASK (0x7<<AIAO_I2S_TDM_3_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_3_SDI_IN_SEL_I2S_TDM_0_SDO_OUT (0x0<<AIAO_I2S_TDM_3_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_3_SDI_IN_SEL_I2S_TDM_1_SDO_OUT (0x1<<AIAO_I2S_TDM_3_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_3_SDI_IN_SEL_I2S_TDM_2_SDO_OUT (0x2<<AIAO_I2S_TDM_3_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_3_SDI_IN_SEL_SDI_IN_I2S0 (0x4<<AIAO_I2S_TDM_3_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_3_SDI_IN_SEL_SDI_IN_I2S1 (0x5<<AIAO_I2S_TDM_3_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_3_SDI_IN_SEL_SDI_IN_I2S2 (0x6<<AIAO_I2S_TDM_3_SDI_IN_SEL_POS)
#define AIAO_I2S_TDM_3_SDI_IN_SEL_SDI_IN_I2S3 (0x7<<AIAO_I2S_TDM_3_SDI_IN_SEL_POS)

#define AIAO_I2S_TDM_0_SDO_OUT_SEL_POS (0)
#define AIAO_I2S_TDM_0_SDO_OUT_SEL_MASK (0x7<<AIAO_I2S_TDM_0_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_0_SDO_OUT_SEL_CODEC (0x4<<AIAO_I2S_TDM_0_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_1_SDO_OUT_SEL_POS (4)
#define AIAO_I2S_TDM_1_SDO_OUT_SEL_MASK (0x7<<AIAO_I2S_TDM_1_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_1_SDO_OUT_SEL_SDO_I2S0 (0x4<<AIAO_I2S_TDM_1_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_1_SDO_OUT_SEL_SDO_I2S1 (0x5<<AIAO_I2S_TDM_1_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_1_SDO_OUT_SEL_SDO_I2S2 (0x6<<AIAO_I2S_TDM_1_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_1_SDO_OUT_SEL_SDO_I2S3 (0x7<<AIAO_I2S_TDM_1_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_2_SDO_OUT_SEL_POS (8)
#define AIAO_I2S_TDM_2_SDO_OUT_SEL_MASK (0x7<<AIAO_I2S_TDM_2_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_2_SDO_OUT_SEL_I2S0 (0x4<<AIAO_I2S_TDM_2_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_2_SDO_OUT_SEL_I2S1 (0x5<<AIAO_I2S_TDM_2_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_2_SDO_OUT_SEL_I2S2 (0x6<<AIAO_I2S_TDM_2_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_2_SDO_OUT_SEL_I2S3 (0x7<<AIAO_I2S_TDM_2_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_3_SDO_OUT_SEL_POS (12)
#define AIAO_I2S_TDM_3_SDO_OUT_SEL_MASK (0x7<<AIAO_I2S_TDM_3_SDO_OUT_SEL_POS)
#define AIAO_I2S_TDM_3_SDO_OUT_SEL_CODEC (0x7<<AIAO_I2S_TDM_3_SDO_OUT_SEL_POS)

#define AIAO_I2S1_BCLK_OEN_SEL (1<<1)
#define AIAO_I2S2_BCLK_OEN_SEL (1<<2)
#define AIAO_I2S3_BCLK_OEN_SEL (1<<3)
#define AIAO_I2S0_BCLK_OEN_EXT (1<<8)
#define AIAO_I2S1_BCLK_OEN_EXT (1<<9)
#define AIAO_I2S2_BCLK_OEN_EXT (1<<10)
#define AIAO_I2S3_BCLK_OEN_EXT (1<<11)
#define AIAO_I2S_BCLK_OEN_NO_DELAY (1<<16)

#define AIAO_AUDIO_PDM_SEL_I2S_IO_GENERAL 0
#define AIAO_AUDIO_PDM_SEL_I2S_IO_I2S1_PDM 1
#define AIAO_AUDIO_PDM_SEL_I2S_IO_I2S2_PDM 2


#ifdef __cplusplus
}
#endif

#endif /* AIAO_H */