/******************************************************************************************
  Filename    : codec.h

  Core        : T-Head XuanTie C906 (RV64)
  
  SoC         : CVITEK CV1800B (Milk-V Duo)
    
  Author      : emeb
 
  Owner       : emeb
  
  Date        : 04.18.2026
  
  Description : CODEC peripheral header file
  
******************************************************************************************/

#ifndef CODEC_H
#define CODEC_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @struct  CODEC_TypeDef
 * @brief   CODEC Register Layout
 */
typedef struct {
    volatile uint32_t txdac_ctrl0;	/* 0x000: */
	volatile uint32_t txdac_ctrl1;	/* 0x004: */
	volatile uint32_t txdac_status;	/* 0x008: */
	volatile uint32_t txdac_afe0;	/* 0x00c: */
	volatile uint32_t txdac_afe1;	/* 0x010: */
	uint32_t RESERVED_0[3];			/* 0x014 - 0x01c */
	volatile uint32_t txdac_ana0;	/* 0x020: */
	volatile uint32_t txdac_ana1;	/* 0x024: */
	uint32_t RESERVED_1[55];		/* 0x028 - 0x0fc */
	volatile uint32_t rxadc_ctrl0;	/* 0x100: */
	volatile uint32_t rxadc_ctrl1;	/* 0x104: */
	volatile uint32_t rxadc_status;	/* 0x108: */
	uint32_t RESERVED_2;			/* 0x10c */
	volatile uint32_t rxadc_ana0;	/* 0x110: */
	volatile uint32_t rxadc_ana1;	/* 0x114: */
	volatile uint32_t rxadc_ana2;	/* 0x118: */
	volatile uint32_t rxadc_ana3;	/* 0x11c: */
	volatile uint32_t rxadc_ana4;	/* 0x120: */
} CODEC_TypeDef;

/* Peripheral Base Definitions */
#define CODEC_BASE    (0x0300a000ull)

/* Instance Pointers */
#define CODEC    ((CODEC_TypeDef *)CODEC_BASE)

/* Register fields */
#define CODEC_TXDAC_CTRL0_TXDAC_EN (1)
#define CODEC_TXDAC_CTRL0_I2S_RX_EN (1<<1)
#define CODEC_TXDAC_CTRL1_TXDAC_CIC_OPT_64 (0)
#define CODEC_TXDAC_CTRL1_TXDAC_CIC_OPT_128 (1)
#define CODEC_TXDAC_CTRL1_TXDAC_CIC_OPT_256 (2)
#define CODEC_TXDAC_CTRL1_TXDAC_CIC_OPT_)
#define CODEC_TXDAC_CTRL1_TXDAC_DEM_TYPE_ROT (0<<4)
#define CODEC_TXDAC_CTRL1_TXDAC_DEM_TYPE_MIN (1<<4)
#define CODEC_TXDAC_CTRL1_TXDAC_DEM_TYPE_THM2 (2<<4)
#define CODEC_TXDAC_CTRL1_TXDAC_DEM_TYPE_THM3 (3<<4)
#define CODEC_TXDAC_CTRL1_TXDAC_DSM_OPT_ORD1 (1<<8)
#define CODEC_TXDAC_CTRL1_TXDAC_ZCD_EN (1<<9)
#define CODEC_TXDAC_CTRL1_TXDAC_FSM_SRC_SEL_I2S0 (1<<10)
#define CODEC_TXDAC_CTRL1_TXDAC_DITHER_OPT_POS (12)
#define CODEC_TXDAC_CTRL1_TXDAC_DITHER_OPT_MASK (7<<CODEC_TXDAC_CTRL1_TXDAC_DITHER_OPT_POS)
#define CODEC_TXDAC_STATUS_FSM_POS (0)
#define CODEC_TXDAC_STATUS_FSM_MASK (7)
#define CODEC_TXDAC_STATUS_AFE_FSM_POS (4)
#define CODEC_TXDAC_STATUS_AFE_FSM_MASK (7<<CODEC_TXDAC_STATUS_AFE_FSM_POS)
#define CODEC_TXDAC_STATUS_DAC_L_GAIN_POS (8)
#define CODEC_TXDAC_STATUS_DAC_L_GAIN_MASK (0x1ff<<CODEC_TXDAC_STATUS_DAC_L_GAIN_POS)
#define CODEC_TXDAC_STATUS_DAC_R_GAIN_POS (20)
#define CODEC_TXDAC_STATUS_DAC_R_GAIN_MASK (0x1ff<<CODEC_TXDAC_STATUS_DAC_R_GAIN_POS)
#define CODEC_TXDAC_AFE0_INIT_DLY_CNT_POS (0)
#define CODEC_TXDAC_AFE0_INIT_DLY_CNT_MASK (0x3f)
#define CODEC_TXDAC_AFE0_VALUE_TICK_POS (8)
#define CODEC_TXDAC_AFE0_VALUE_TICK_MASK (0xff<<CODEC_TXDAC_AFE0_VALUE_TICK_POS)
#define CODEC_TXDAC_AFE0_GAIN_TICK_POS (16)
#define CODEC_TXDAC_AFE0_GAIN_TICK_MASK (0xfff<<CODEC_TXDAC_AFE0_GAIN_TICK_POS)
#define CODEC_TXDAC_AFE1_GAIN_UB0_POS (0)
#define CODEC_TXDAC_AFE1_GAIN_UB0_MASK (0x1ff)
#define CODEC_TXDAC_AFE1_GAIN_UB1_POS (16)
#define CODEC_TXDAC_AFE1_GAIN_UB1_MASK (0x1ff<<CODEC_TXDAC_AFE1_GAIN_UB1_POS)
#define CODEC_TXDAC_AFE1_RAMP_BP (1<<28)
#define CODEC_TXDAC_ANA0_TSEL_POS (4)
#define CODEC_TXDAC_ANA0_TSEL_MASK (0x3<<CODEC_TXDAC_ANA0_TSEL_POS)
#define CODEC_TXDAC_ANA0_VSEL_POS (8)
#define CODEC_TXDAC_ANA0_VSEL_MASK (0x3<<CODEC_TXDAC_ANA0_VSEL_POS)
#define CODEC_TXDAC_ANA1_DA_EN_TXDAC_OW_VAL (1)
#define CODEC_TXDAC_ANA1_DA_END2US_TXDAC_OW_VAL (1<<1)
#define CODEC_TXDAC_ANA1_DA_EN_TXDAC_OW_EN (1<<16)
#define CODEC_TXDAC_ANA1_DA_END2US_TXDAC_OW_EN (1<<17)
#define CODEC_RXADC_CTRL0_RXADC_EN (1)
#define CODEC_RXADC_CTRL0_I2S_TX_EN (1<<1)
#define CODEC_RXDAC_CTRL1_RXADC_CIC_OPT_64 (0)
#define CODEC_RXDAC_CTRL1_RXADC_CIC_OPT_128 (1)
#define CODEC_RXDAC_CTRL1_RXADC_CIC_OPT_256 (2)
#define CODEC_RXDAC_CTRL1_RXADC_CIC_OPT_512 (3)
#define CODEC_RXDAC_CTRL1_RXADC_CHAN_SWAP (1<<2)
#define CODEC_RXDAC_CTRL1_RXADC_SINGLE (1<<3)
#define CODEC_RXDAC_CTRL1_RXADC_DCB_OPT_BYPASS (0<<4)
#define CODEC_RXDAC_CTRL1_RXADC_DCB_OPT_2_8 (1<<4)
#define CODEC_RXDAC_CTRL1_RXADC_DCB_OPT_2_9 (2<<4)
#define CODEC_RXDAC_CTRL1_RXADC_DCB_OPT_2_10 (3<<4)
#define CODEC_RXDAC_CTRL1_RXADC_DCB_OPT_2_11 (4<<4)
#define CODEC_RXDAC_CTRL1_RXADC_DCB_OPT_2_12 (5<<4)
#define CODEC_RXDAC_CTRL1_RXADC_IGR_INIT (1<<8)
#define CODEC_RXDAC_CTRL1_RXADC_CLK_FORCE_EN (1<<9)
#define CODEC_RXDAC_CTRL1_RXADC_FSM_SRC_SEL (1<<10)
#define CODEC_RXDAC_STATUS_CIC0_INIT_DONE (1)
#define CODEC_RXDAC_STATUS_FIR1_0_INIT_DONE (1<<1)
#define CODEC_RXDAC_STATUS_FIR2_0_INIT_DONE (1<<2)
#define CODEC_RXDAC_STATUS_CIC1_INIT_DONE (1<<4)
#define CODEC_RXDAC_STATUS_FIR1_1_INIT_DONE (1<<5)
#define CODEC_RXDAC_STATUS_FIR2_1_INIT_DONE (1<<6)
#define CODEC_RXDAC_ANA0_GSTEPL_RXPGA_POS (0)
#define CODEC_RXDAC_ANA0_GSTEPL_RXPGA_MASK (0x1fff)
#define CODEC_RXDAC_ANA0_G6DBL_RXPGA (1<<13)
#define CODEC_RXDAC_ANA0_GAINL_RXADC_POS (14)
#define CODEC_RXDAC_ANA0_GAINL_RXADC_MASK (0x3<<CODEC_RXDAC_ANA0_GAINL_RXADC_POS)
#define CODEC_RXDAC_ANA0_GSTEPR_RXPGA_POS (16)
#define CODEC_RXDAC_ANA0_GSTEPR_RXPGA_MASK (0x1fff<<CODEC_RXDAC_ANA0_GSTEPR_RXPGA_POS)
#define CODEC_RXDAC_ANA0_G6DBR_RXPGA (1<<29)
#define CODEC_RXDAC_ANA0_GAINR_RXADC_POS (30)
#define CODEC_RXDAC_ANA0_GAINR_RXADC_MASK (0x3<<CODEC_RXDAC_ANA0_GAINR_RXADC_POS)
#define CODEC_RXDAC_ANA1_GAINL_STATUS_POS (0)
#define CODEC_RXDAC_ANA1_GAINL_STATUS_MASK (0xFFFF)
#define CODEC_RXDAC_ANA1_GAINR_STATUS_POS (16)
#define CODEC_RXDAC_ANA1_GAINR_STATUS_MASK (0xFFFF<<CODEC_RXDAC_ANA1_GAINR_STATUS_POS)
#define CODEC_RXDAC_ANA2_MUTEL_RXPGA (1)
#define CODEC_RXDAC_ANA2_MUTER_RXPGA (1<<1)
#define CODEC_RXDAC_ANA2_DIFF_EN_RXPGA (1<<16)
#define CODEC_RXDAC_ANA2_TRISTATE_RXPGA (1<<19)
#define CODEC_RXDAC_ANA3_ADDI_RXADC (1)
#define CODEC_RXDAC_ANA3_CKSEL_RXADC (1<<1)
#define CODEC_RXDAC_ANA3_EN_ASAR_I_RXADC (1<<2)
#define CODEC_RXDAC_ANA3_EN_ASAR_Q_RXADC (1<<3)
#define CODEC_RXDAC_ANA3_DEM_TYPE_RXADC_ROT (0<<4)
#define CODEC_RXDAC_ANA3_DEM_TYPE_RXADC_MIN (1<<4)
#define CODEC_RXDAC_ANA3_CTUNE_RXADC_POS (8)
#define CODEC_RXDAC_ANA3_CTUNE_RXADC_MASK (0xf<<CODEC_RXDAC_ANA3_CTUNE_RXADC_POS)
#define CODEC_RXDAC_ANA3_EN_DITHER_RXADC (1<<12)
#define CODEC_RXDAC_ANA3_RSTSDM_RXADC (1<<13)
#define CODEC_RXDAC_ANA3_EN_VCMT_RXADC (1<<14)
#define CODEC_RXDAC_ANA3_VLDO0P9_RXADC_085 (0<<16)
#define CODEC_RXDAC_ANA3_VLDO0P9_RXADC_090 (1<<16)
#define CODEC_RXDAC_ANA3_VLDO0P9_RXADC_095 (2<<16)
#define CODEC_RXDAC_ANA3_VLDO0P9_RXADC_100 (3<<16)
#define CODEC_RXDAC_ANA3_VLDO12_RXADC_110 (0<<18)
#define CODEC_RXDAC_ANA3_VLDO12_RXADC_115 (1<<18)
#define CODEC_RXDAC_ANA3_VLDO12_RXADC_120 (2<<18)
#define CODEC_RXDAC_ANA3_VLDO12_RXADC_125 (3<<18)
#define CODEC_RXDAC_ANA3_RNLVL_RXADC_0 (0<<20)
#define CODEC_RXDAC_ANA3_RNLVL_RXADC_1 (1<<20)
#define CODEC_RXDAC_ANA3_RNLVL_RXADC_2 (2<<20)
#define CODEC_RXDAC_ANA3_RNLVL_RXADC_3 (3<<20)
#define CODEC_RXDAC_ANA4_DA_EN_RXPGA_STATUS (1)
#define CODEC_RXDAC_ANA4_DA_END2US_RXPGA_STATUS (1<<1)
#define CODEC_RXDAC_ANA4_DA_EN_RXADC_STATUS (1<<2)
#define CODEC_RXDAC_ANA4_DA_EN_AUDBIAS_STATUS (1<<3)
#define CODEC_RXDAC_ANA4_AD_DOL_RXADC_POS (16)
#define CODEC_RXDAC_ANA4_AD_DOL_RXADC_MASK (0x7<<CODEC_RXDAC_ANA4_AD_DOL_RXADC_POS)
#define CODEC_RXDAC_ANA4_AD_DOR_RXADC_POS (20)
#define CODEC_RXDAC_ANA4_AD_DOR_RXADC_MASK (0x7<<CODEC_RXDAC_ANA4_AD_DOR_RXADC_POS)

#ifdef __cplusplus
}
#endif

#endif /* CODEC_H */